name: Build Docker image

on:
  push:
#    branches:
#      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - # Check out repository
        name: Checkout
        uses: actions/checkout@v3
      - # Set up QEMU for multiarch support
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - # Set up Docker BuildX for Docker image building
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - # Set proper tags
        name: Docker metadata
        id: docker_meta # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          images: bilde2910/hauk
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=stable-{{major}}.x
      - # Log in to Docker Hub
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # Build and push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
